Models/Contacto.cs
namespace LaPiranaPractice.Models
{
    public class Contacto
    {
        public int Id { get; set; }
        public string NombreCompleto { get; set; }
        public string Asunto { get; set; }
        public string Mensaje { get; set; }
    }
}

Models/PiranaContext.cs
using Microsoft.EntityFrameworkCore;

namespace LaPiranaPractice.Models
{
    public class PiranaContext : DbContext
    {
        public DbSet<Contacto> Contactos { get; set; }
        public DbSet<Producto> Productos { get; set; }
        public PiranaContext(DbContextOptions dco) : base(dco){
            
        }
    }
}

Models/Producto.cs
namespace LaPiranaPractice.Models
{
    public class Producto
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public decimal precio { get; set; }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using LaPiranaPractice.Models;

namespace LaPiranaPractice.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }
//--------------------------------PRESENTACION DE LA EMPRESA---------------------------
        //Página: QUIENES SOMOS
        public IActionResult Index()
        {
            return View();
        }

        //Página: Servicios y Productos
        public IActionResult Servicios()
        {
            return View();
        }
        
        //Página: FORMULARIO Contacto
        public IActionResult Contacto()
        {
            return View();
        }

        //Página: Recibe datos de FORMULARIO Contacto
        [HttpPost]
        public IActionResult Contacto(String datos)
        {
            return View();
        }

        //Página: Confirmación de recepcion de datos de FORMULARIO Contacto
        public IActionResult ContactoConfirmacion()
        {
            return View();
        }
//----------------------------------PRODUCTOS Y SERVICIOS-------------------------------
    }
}

Controllers/VentasController.cs
using Microsoft.AspNetCore.Mvc;

namespace LaPiranaPractice.Controllers
{
    public class VentasController : Controller
    {
        public IActionResult Servicios(){
            return View();
        }
        public IActionResult Productos(){
            return View();
        }
        public IActionResult ProductosDestacados(){
            return View();
        }
    }
}

Views/Home/Contacto.cshtml
@{
    ViewData["Title"] = "Contacto";
}

<div class="text-center">
    <h1 class="display-4">Contacto</h1>
</div>

Views/Home/ContactoConfirmacion.cshtml
@{
    ViewData["Title"] = "Contacto";
}

<div class="text-center">
    <h1 class="display-4">Contacto</h1>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Home/Servicios.cshtml
<h1>SERVICIOS</h1>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LaPiranaPractice</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src=/PufferfushIcon.png />
                    </a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">¿Quiénes somos?</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Servicios">Qué ofrecemos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contacto">Contacto</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ventas" asp-action="Productos">Productos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ventas" asp-action="ProductosDestacados">Productos Destacados</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ventas" asp-action="Servicios">Servicios</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - LaPiranaPractice - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Ventas/Productos.cshtml
<h1>PRODUCTOS</h1>

Views/Ventas/ProductosDestacados.cshtml
<h1>PRODUCTOS DESTACADOS</h1>

Views/Ventas/Servicios.cshtml
<h1>SERVICIOS</h1>